### PR TITLE
Allow codeception/codeception v4

### PR DESCRIPTION
**Pull request by yesdevnull**
Quick one to bump Codeception version to v4.

### CODE REVIEW

**Comment by bensquire** [comment]
It would be great if we can get it merged in?

**Comment by kornrunner** [comment]
Just a reminder :)

**Comment by Naktibalda** [comment]
Does it work? :)

**Comment by Naktibalda** [comment]
If someone could implement and test simple changes I requested in #16 , I would merge that PR and make a new release.

**Comment by Naktibalda** [comment]
Please mention me in the new pull request because I don't follow this repository.

**Comment by Naktibalda** [comment]
I released 0.4.0 version.

**Pull request merged**
